Bug #1079807 UPGRADE: to v4.14.181 from android-4.14-stable
[self test   ] L.A.V.A
[change_type ] r&d

Merge android-4.14-stable: v5.4.181 into sprdlinux4.14.

1) Following files is being processed for conflicts:

  -- net/ipv4/sysctl_net_ipv4.c @Wade.Shu
  -- arch/arm64/kernel/traps.c @Zhiguo.Niu
  -- fs/f2fs/checkpoint.c @Zhiguo.Niu

2) There is Google issue [1] related to this patch.

VTS test failed while reporting
"Missing config CONFIG_SECURITY_PERF_EVENTS_RESTRICT" but which
is already reverted in 4.14-stable.

We need to upgrade and re-test vts.

3) sprd_*_defconfig are being updated by scripts.

4) Following build error was fixed:

  -- dtbo_merge_chk_main @Tianhui.Wang

  -- CONFIG_LBADF 32bit/64bit long issue
     ../fs/f2fs/inode.c: In function 'sanity_check_inode':
     ../fs/f2fs/inode.c:303:4: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'blkcnt_t' [-Werror=format=]
     f2fs_warn(sbi, "%s: inode (ino=%lx) has inconsistent "
     ^
  -- net/xfrm/xfrm_device.c keep old code due to commit 64d1cec4 was not
applied.

[1] https://partnerissuetracker.corp.google.com/issues/157277037

Change-Id: I3e85476f041695363fdfb35e2e0aa426147f2337
Signed-off-by: Orson Zhai <orson.zhai@unisoc.com>